#!/usr/bin/env sh

dateTime() { date +'📅  %a, %e %b ⌚ %H : %M'; }

wifi() {
   connected || echo ❗
   strength="$(awk 'FNR == 3 { printf "%d", $3*100/70 }' /proc/net/wireless)"
   echo "🌐 $strength%"
}

# performance() {

#    cpu="$(top -b -n 1 | awk '(NR==3){
# 	if( $8 == "id," )
# 		print "0"
# 	else
# 		printf "%d", 100 - $8
# 	}')"

#    mem="$(free -m | awk '(NR==2){ printf "%d", $3 }')"
#    # u=M

#    temp="$(sensors | awk '(/Core 0/){printf $3}' | sed 's/\.0//; s/+//')"

#    echo "🌡 $temp   🐎 $cpu%   🧠 $mem"

# }

# getStorageInfo(){ df -h "$1" | awk '(NR == 2){print $4}' | sed 's/G//'; }
# storage(){
#     root="$(getStorageInfo /)"
#     home="$(getStorageInfo /home)"
# 	echo "💽 $root  🏠 $home"
# }

pipeDynamic() { while :; do
   echo "$1""$($2)"
   sleep "$3"
done > "$PANEL_FIFO" & }

