#!/usr/bin/env sh

dateTime() { date +'📅  %a, %e %b ⌚ %H : %M'; }

wifi() {
   connected || echo ❗ 000%
   strength="$(awk 'FNR == 3 { printf "%d", $3*100/70 }' /proc/net/wireless)"
   echo "🌐 $strength%"
}

performance() {

   cpu="$(top -b -n 1 | awk '(NR==3){
	if( $8 == "id," )
		print "00"
	else
		printf "%02d", 100 - $8
	}')"

   mem="$(free -m | awk '(NR==2){ printf "%04d", $3 }')"
   # u=M

   temp="$(sensors | awk '(/Core 0/){printf $3}' | sed 's/\.0//; s/+//')"

   echo "🌡 $temp   🐎 $cpu%   🧠 $mem"

}

# getStorageInfo(){ df -h "$1" | awk '(NR == 2){print $4}' | sed 's/G//'; }
# storage(){
#     root="$(getStorageInfo /)"
#     home="$(getStorageInfo /home)"
# 	echo "💽 $root  🏠 $home"
# }

coronaStatBangladesh() {
   connected || exit

   country=${1:-bangladesh}

   report=$(curl -s https://corona-stats.online/"$country" | grep -i "$country" | sed "s/\s*//g; s/[▲║]//g; s/│/;/g; s/\x1b\[[0-9;]*m//g")
   confirmed=$(echo "$report" | cut -d ';' -f 3)
   recovered=$(echo "$report" | cut -d ';' -f 7)
   deaths=$(echo "$report" | cut -d ';' -f 5)

   echo "😷 $confirmed 😀 $recovered 💀 $deaths"
}

pipeDynamic() { while :; do
   echo "$1""$($2)"
   sleep "$3"
done > "$PANEL_FIFO" & }
