#!/usr/bin/env sh

battery() {
   stat="$(cat /sys/class/power_supply/ADP?/online)"
   [ "$stat" = 1 ] && icon=🔌 || icon=🔋
   cap="$(cat /sys/class/power_supply/BAT?/capacity)"
   echo "$icon $cap"
}

volume() {
   volstat="$(amixer get Master)"
   echo "$volstat" | grep -o -m 1 "off" > /dev/null && echo 🔇 000% ||
      echo 🔊 "$(echo "$volstat" | grep -o -m 1 "[0-9]\+%")"
}

notification() { [ -f "$DONT_DISTURB_MODE" ] && echo 🔕 || echo 🔔; }

recording() {
   case "$1" in
      a) echo "⏺🎙" ;;
      w) echo "⏺🎥" ;;
      s) echo "⏺💻" ;;
      o) echo "" ;;
   esac
}


mail() {
   unread=$(find ~/.local/share/mail/gmail/INBOX/new/* -type f 2> /dev/null |
      wc -l)
   echo "📫  $unread"
}

pipeStatic() { echo "$1""$("$2")" > "$PANEL_FIFO" & }

