#!/usr/bin/env sh

del="  |  "

while read -r line; do

   case $line in
      d*) dt="${line#?}" ;;
      m*) mail="${line#?}" ;;
      n*) not="${line#?}" ;;
      p*) per="${line#?}" ;;
      r*) rec="${line#?}" ;;
      v*) vol="${line#?}" ;;
      w*) wif="${line#?}" ;;

      W*)
         wm=
         IFS=':'
         set -- ${line#?}
         while [ "$#" -gt 0 ]; do
            item="$1"
            name="${item#?}"
            case "$item" in
               [mMfFoOuULG]*)
                  case "$item" in
                     [FOU]*) name=" 🏚 " ;;
                     f*) name=" 🕳 " ;;
                     o*) name=" 🌴 " ;;
                     LM | G*?) name="" ;;
                     *) name="" ;;
                  esac
                  wm="${wm} ${name}"
                  ;;
            esac
            shift
         done
         ;;

   esac

   printf "%s\r" \
      "$wif $del $mail $del $not $del $vol $del $wm $del $per $del $dt $rec"

done < "$PANEL_FIFO"

